In [1]:
import numpy as np
import pandas as pd

In [4]:
from tensorflow.keras import datasets

In [5]:
(x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 101s 9us/step


In [6]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
x_train.shape

(60000, 28, 28)

In [8]:
x_test.shape

(10000, 28, 28)

In [9]:
width,height = 28,28
input_shape = (width,height, 1)

In [10]:
input_shape

(28, 28, 1)

In [14]:
x_train = x_train.reshape(x_train.shape[0],height,width, 1)
x_test = x_test.reshape(x_test.shape[0],height,width, 1)

In [15]:
x_train.shape

(60000, 28, 28, 1)

In [16]:
x_test.shape

(10000, 28, 28, 1)

In [17]:
y_train.shape

(60000,)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size = 0.1)

In [20]:
len(x_train)

54000

In [21]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [22]:
x_train

array([[[[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]],

        [[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]],

        [[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]],

        ...,

        [[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]],

        [[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]],

        [[-0.42405003],
         [-0.42405003],
         [-0.42405003],
         ...,
         [-0.42405003],
         [-0.42405003],
         [-0.42405003]]],


       [[[-0.42405003],


In [24]:
y_train

array([7, 1, 5, ..., 0, 4, 6], dtype=uint8)

In [25]:
from tensorflow import keras

In [27]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [28]:
y_train

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

Model

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Dropout , Flatten , Input , Conv2D , MaxPool2D , AveragePooling2D

In [33]:
model = Sequential()

model.add(Conv2D(6, kernel_size=(5,5),strides=(1, 1), activation='tanh',input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size=(5,5),strides=(1, 1)))
model.add(Conv2D(6, kernel_size=(5,5),strides=(1, 1), activation='tanh',input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size=(5,5),strides=(1, 1)))
model.add(Conv2D(6, kernel_size=(5,5),strides=(1, 1), activation='tanh',input_shape = (28,28,1)))

model.add(Flatten())
model.add(Dense(84, activation='tanh'))
model.add(Dense(num_labels, activation='softmax'))

In [34]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 24, 24, 6)      │           156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d               │ (None, 20, 20, 6)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 16, 16, 6)      │           906 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ average_pooling2d_1             │ (None, 12, 12, 6)      │             0 │
│ (AveragePooling2D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 8, 8, 6)        │           906 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 384)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 84)             │        32,340 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           850 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,158 (137.34 KB)

 Trainable params: 35,158 (137.34 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer='adam',metrics=['accuracy'])

In [37]:
history = model.fit(x_train,y_train, batch_size = 32, epochs = 5, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 18s 11ms/step - accuracy: 0.9851 - loss: 0.0463 - val_accuracy: 0.9743 - val_loss: 0.0833
Epoch 2/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.9853 - loss: 0.0464 - val_accuracy: 0.9823 - val_loss: 0.0625
Epoch 3/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.9874 - loss: 0.0410 - val_accuracy: 0.9815 - val_loss: 0.0628
Epoch 4/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.9874 - loss: 0.0419 - val_accuracy: 0.9833 - val_loss: 0.0560
Epoch 5/5
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9872 - loss: 0.0403 - val_accuracy: 0.9843 - val_loss: 0.0578


In [38]:
score = model.evaluate(x_test,y_test,verbose = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9816 - loss: 0.0589


In [39]:
score

[0.0513768307864666, 0.9843999743461609]